[tool.poetry]
name = "pkg-c"
version = "0.1.0"
description = ""
authors = ["Jan Lukány <lukany.jan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
